= dita-topic

`dita-topic` is a custom converter for Asciidoctor that converts a single AsciiDoc file to a corresponding DITA 1.3 topic.

In combination with link:https://github.com/jhradilek/asciidoctor-dita-vale[asciidoctor-dita-vale], link:https://github.com/jhradilek/dita-custom-xslt#installation[dita-convert], and link:https://github.com/jhradilek/fix-dita-links[dita-cleanup], this project can be used to rapidly convert AsciiDoc content to DITA:

. Identify incompatible markup in the AsciiDoc source file:
+
[literal,subs="+quotes"]
....
$ *vale _source_file.adoc_*
....

. Convert the AsciiDoc file to a generic DITA topic:
+
[literal,subs="+quotes"]
....
$ *dita-topic _source_file.adoc_*
....

. Convert the generic DITA topic to a specialized DITA concept, reference, or task:
+
[literal,subs="+quotes"]
....
$ *dita-convert -g _source_file.dita_ -o _output_file.dita_*
....

. _Optional:_ Clean up the resulting DITA file if necessary:
+
[literal,subs="+quotes"]
....
$ *dita-cleanup -iI -D ../images -X . _output_file.dita_*
....

[#install]
== Installation

Install the `asciidoctor-dita-topic` Ruby gem:

[literal,subs="+quotes"]
....
$ *gem install asciidoctor-dita-topic*
....

[IMPORTANT]
====
On macOS, `asciidoctor` installed with Homebrew expects Ruby gems in a different directory than where `gem install` places them. To work around this issue, you can either link:https://docs.asciidoctor.org/asciidoctor/latest/install/ruby-packaging/#gem-install[install `asciidoctor` as a Ruby gem], or run `asciidoctor` with the `-r` option followed by the relative path to the `dita-topic.rb` file.
====

[#use]
== Usage

To convert an AsciiDoc file to a generic DITA topic, run the supplied `dita-topic` command-line interface as follows:

[literal,subs="+quotes"]
....
$ *dita-topic _your_file_.adoc*
....

This creates a new file, `_your_file_.dita`, in the same directory as `_your_file_.adoc`. You can also convert multiple files at the same time:

[literal,subs="+quotes"]
....
$ **dita-topic *.adoc**
....

The command-line interface simplifies the code execution and provides a few options in addition to the conversion. However, if you prefer to use Asciidoctor directly, load the converter with the `-r dita-topic` option and then select `dita-topic` as the backend output format with `-b dita-topic`:

[literal,subs="+quotes"]
....
$ *asciidoctor -r dita-topic -b dita-topic _your_file_.adoc*
....

[IMPORTANT]
====
`dita-topic` does not validate the converted content. If you have link:https://www.dita-ot.org/[DITA Open Toolkit] installed, you can verify that the converted file can be built as follows:

[literal,subs="+quotes"]
....
$ **dita -i _your_file_.dita -f xhtml**
....

To produce slightly more readable errors, you can also use `xmlstarlet`:

[literal,subs="+quotes"]
....
$ **xmlstarlet val -e -s _path_to_dita-ot_directory_/plugins/org.oasis-open.dita.v1_3/schema-url/technicalContent/xsd/topic.xsd _converted_file_.dita**
....
====

[#attributes]
=== Supplying individual attribute definitions

If your AsciiDoc files use attributes that are defined outside of these files, you can supply the attribute definitions on the command line with the `-a _attribute_=_value_` option:

[literal,subs="+quotes"]
....
$ **dita-topic -a _attribute_=_value_ _your_file_.adoc**
....

If you prefer to use Asciidoctor directly, supply the attribute definitions with the `-a _attribute_=_value_` option as follows:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a _attribute_=_value_ _your_file_.adoc**
....

You can provide multiple `-a` options at the same time. Providing relevant attribute definitions is especially important if your document contains conditional content.

[#attribute_files]
=== Supplying attribute definition files

If listing individual attribute definitions is impractical, you can use the `-p _definition_file_.adoc` option to supply another AsciiDoc file with attribute definitions in it:

[literal,subs="+quotes"]
....
$ **dita-topic -p _definition_file_.adoc _your_file_.adoc**
....

The supplied file is automatically prepended to each AsciiDoc file during conversion. You can provide multiple `-p` options at the same time or use a combination `-p` and `-a` options to construct your attribute definitions. If you define the same attribute twice this way, the value defined by using the `-a` option takes precedence.

This functionality is not available in standard Asciidoctor.

[#authors]
=== Enabling author lines

AsciiDoc topics are expected to be included in other files and therefore should not contain link:https://docs.asciidoctor.org/asciidoc/latest/document/author-line/[author line] definitions. In most cases, lines that directly follow the topic title are intended as first paragraphs. For this reason, author lines are disabled by default. To avoid losing content during conversion, as a workaround, the `dita-topic` converter interprets the raw content of the author line as a paragraph and issues a warning.

To enable processing of author lines as metadata, run the `dita-topic` command with the `-l` option:

[literal,subs="+quotes"]
....
$ **dita-topic -l _your_file_.adoc**
....

If you prefer to use Asciidoctor directly, set the value of the `dita-topic-authors` to `on`:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a dita-topic-authors=on _your_file_.adoc**
....

[#titles]
=== Disabling floating titles

Unlike AsciiDoc, DITA does not support floating titles and only allows titles to be assigned to a limited number of elements. To avoid losing content during conversion, as a workaround, the `dita-topic` converter uses the following markup by default:

[source,xml]
----
<p outputclass="title"><b>Floating title</b></p>
----

To disable this behavior, run the `dita-topic` command with the `-T` option:

[literal,subs="+quotes"]
....
$ **dita-topic -T _your_file_.adoc**
....

If you prefer to use Asciidoctor directly, set the value of the `dita-topic-titles` to `off`:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a dita-topic-titles=off _your_file_.adoc**
....

[#callouts]
=== Disabling callouts

Unlike AsciiDoc, DITA does not support callouts as a method to add annotations to specific lines in verbatim blocks. To avoid losing content during conversion, as a workaround, the `dita-topic` converter uses XML entities for circled numbers.

To disable this behavior, run the `dita-topic` command with the `-C` option:

[literal,subs="+quotes"]
....
$ **dita-topic -C _your_file_.adoc**
....

If you prefer to use Asciidoctor directly, set the value of the `dita-topic-callouts` to `off`:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a dita-topic-callouts=off _your_file_.adoc**
....

[#includes]
=== Disabling include directives

By default, Asciidoctor resolves all `include` directives before converting the file. To only convert the contents of the selected file, run the `dita-topic` command with the `-I` option:

[literal,subs="+quotes"]
....
$ **dita-topic -I _your_file_.adoc**
....

If you prefer to use Asciidoctor directly, there is no direct equivalent to this functionality. As a workaround, you can specify the `-S secure` option:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -S secure _your_file_.adoc**
....

This disables processing of the include directives, but leaves cross references to the included files in the converted output.

[#abstracts]
=== Adding short descriptions

DITA provides the `<shortdesc>` element which allows the user to describe the purpose of the topic and is often used as preview text in search results. To replicate this behavior, the `dita-topic` converter recognizes a paragraph preceded by the `[role="_abstract"]` attribute list and adds the `outputclass="abstract"` attribute to it. The link:https://github.com/jhradilek/dita-custom-xslt#installation[dita-convert Python package] transforms such a paragraph to `<shortdesc>` during conversion to a specialized DITA concept, reference, or task.

For example, to designate a paragraph as a short description, use the following AsciiDoc markup:

[source,asciidoc]
----
[id="topic-id"]
= Procedure title

[role="_abstract"]
A short description of the procedure module and what it helps the
user accomplish.

An introductory paragraph.
----

[#semantics]
=== Adding semantic markup

Unlike AsciiDoc, DITA provides a number of semantic elements for software components such as file names, commands, or command-line options. To replicate this behavior, the `dita-topic` converter recognizes the following link:https://docs.asciidoctor.org/asciidoc/latest/attributes/role/#assign-roles-to-formatted-inline-elements[roles] assigned to monospace (```) inline text:

[cols="1,1,2"]
|===
| AsciiDoc Role
| DITA Element
| Description

| command
| `<cmdname>`
| A command name.

| directory
| `<filepath>`
| A directory name.

| filename
| `<filepath>`
| A file name.

| option
| `<option>`
| An command-line option.

| variable
| `<varname>`
| A variable name.
|===

For example, to describe a file name, use the following AsciiDoc markup:

[source,asciidoc]
----
Read the [filename]`/etc/passwd` file to see the complete list of
available user accounts.
----

[#metadata]
=== Adding metadata

DITA provides four metadata attributes that can be used for conditional processing. To replicate this behavior, the `dita-topic` converter recognizes the following link:https://docs.asciidoctor.org/asciidoc/latest/attributes/role/#assign-roles-to-formatted-inline-elements[roles] assigned to inline and block elements:

[cols="1,1,2"]
|===
| AsciiDoc Role
| DITA Attribute
| Description

| `platform:__value__`
| `platform="_value_"`
| Operating system or hardware architecture.

| `product:__value__`
| `product="_value_"`
| Product name.

| `audience:__value__`
| `audience="_value_"`
| Target audience.

| `otherprops:__value__`
| `otherprops="_value_"`
| Additional properties.
|===

For example, to indicate that a particular paragraph is relevant for Linux and macOS and is intended for beginners, use the following AsciiDoc markup:

[source,asciidoc]
----
[role="platform:linux platform:mac audience:beginner"]
For more information, see the *bash*(1) manual page.
----

[#warnings]
== Warnings

Despite aspiring to avoid losing content during conversion and produce valid DITA output, there are limitations to what is possible because of the differences between the two markup languages. When the `dita-topic` converter encounters a possible problem, it prints a warning to standard error output in the following format:

[literal,subs="+quotes"]
....
asciidoctor: WARNING: dita-topic: _The warning message_
....

This possible warning messages are as follows:

[horizontal]
Admonition titles not supported in DITA:: AsciiDoc allows you to add a custom title to any admonition by including `._Admonition title_` on the line above it. Unlike AsciiDoc, DITA does not allow titles for admonitions. `dita-topic` issues this warning whenever an admonition has a title defined in the converted AsciiDoc file.

Author lines not enabled for topics:: AsciiDoc interprets the first line that directly follows the document title as an author line. Because topics are not expected to have author lines, `dita-topic` issues this warning when an author line is present in the converted AsciiDoc file.

Block titles not supported in DITA:: AsciiDoc allows you to include `._Block title_` on the line above most of the block elements to assign a custom title to them. Unlike AsciiDoc, DITA only allows titles to be assigned to a limited number of elements. `dita-topic` issues this warning when the `-a dita-topic-titles=off` option is specified and a block title is present in the converted AsciiDoc file.

Callouts not supported in DITA:: AsciiDoc allows you to use `<1>`, `<2>`, `<3>` and so on in verbatim blocks to add annotations to the specific lines. Unlike AsciiDoc, DITA does not provide a direct equivalent for this functionality. `dita-topic` issues this warning when the `-a dita-topic-callouts=off` option is specified and these annotations are present in the converted AsciiDoc file.

Examples not supported within _object_ in DITA:: AsciiDoc allows you to use an example block anywhere in the document. Unlike AsciiDoc, DITA only allows examples to appear directly in the topic body. `dita-topic` issues a warning whenever an example is nested in another AsciiDoc element.

Floating titles not supported in DITA:: AsciiDoc allows you to use floating titles anywhere in the document. Unlike AsciiDoc, DITA does not support floating titles. `dita-topic` issues this warning when the `-a dita-topic-titles=off` option is specified and a floating title is present in the converted AsciiDoc file.

Inline breaks not supported in DITA:: AsciiDoc provides multiple ways to insert line breaks in paragraphs, such as inserting `{nbsp}+` at the end of the line or specifying `[%hardbreaks]` on the line preceding the paragraph. Unlike AsciiDoc, DITA does not provide direct equivalent for this functionality. `dita-topic` issues this warning whenever an inline line break is present in the converted AsciiDoc file and places the `<!-- break -\->` comment in the output file to mark its place.

Nesting of sections not supported in DITA:: AsciiDoc allows you to nest sections up to 5 levels deep. Unlike AsciiDoc, DITA does not allow the `<section>` elements to be nested. `dita-topic` issues a warning whenever nested sections are present in the converted AsciiDoc file.

Page breaks not supported in DITA:: AsciiDoc allows you to use `<<<` on a separate line to enforce a page break in output formats that support it. Unlike AsciiDoc, DITA does not support page breaks. `dita-topic` issues this warning whenever a page break is present in the converted AsciiDoc file and places the `<p outputclass="page-break"></p>` in the output file to mark its place.

Possible invalid reference: _reference_:: AsciiDoc allows you to cross reference by using an ID no matter if this ID is defined within or outside of the converted document. Unlike AsciiDoc, DITA requires both the target ID and the ID of the target topic to be included in the cross reference if the reference leads outside of the current file. As `dita-topic` is meant to be run on individual AsciiDoc files, it does not have access to information from referenced files during conversion. `dita-topic` issues this warning whenever the cross reference target is not present in the converted AsciiDoc file.

Sidebars not supported in DITA:: AsciiDoc allows you to assign any block the `[sidebar]` block style or enclose it between a pair of `\****` to create a delimited sidebar block. Unlike AsciiDoc, DITA does not support sidebar blocks. `dita-topic` issues this warning when the `-a dita-topic-sidebars=off` option is specified and a sidebar block is present in the converted AsciiDoc file.

STEM support not implemented:: AsciiDoc provides multiple ways to insert Science, Technology, Engineering and Math (STEM) expressions in the document, including the `\stem:[_formula_]` inline macro and the `[stem]` delimited block. `dita-topic` does not implement this feature and issues this warning whenever such an expression is present in the converted AsciiDoc file.

Table footers not supported in DITA:: AsciiDoc allows you to set the `footer` option to mark the last table row as a table footer. Unlike AsciiDoc, DITA does not support table footers. `dita-topic` issues this warning whenever a table footer is present in the converted AsciiDoc file.

Thematic breaks not supported in DITA:: Asciidoc allows you to use `'''`, `---`, or `\***` (the last two with possible optional spaces in between the characters) to insert a thematic break in between two blocks, most commonly represented by a horizontal line. Unlike AsciiDoc, DITA does not support thematic breaks. `dita-topic` issues this warning whenever a thematic break is present in the converted AsciiDoc file.

[#copyright]
== Copyright

Copyright (C) 2024, 2025 Jaromir Hradilek

This program is free software, released under the terms of the link:LICENSE[MIT license]. It is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
