= dita-topic

`dita-topic` is a custom converter for Asciidoctor that converts a single AsciiDoc file to a corresponding DITA topic. To ensured that the generated DITA file is valid, it uses the generic `<topic>` element by default but xref:types[you can enforce] the specialized `<concept>`, `<task>`, or `<reference>` element on the command line.

[#install]
== Installation

Install the `asciidoctor-dita-topic` Ruby gem:

[literal,subs="+quotes"]
....
$ *gem install asciidoctor-dita-topic*
....

[#use]
== Usage

To use the custom converter on the command line, load it with the `-r dita-topic` option and then select `dita-topic` as the backend output format with `-b dita-topic`:

[literal,subs="+quotes"]
....
$ *asciidoctor -r dita-topic -b dita-topic _your_file_.adoc*
....

This creates a new file, `_your_file_.dita`, in the same directory as `_your_file_.adoc`. You can also convert multiple files at the same time:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic *.adoc**
....

[#attributes]
=== Supplying attribute definitions

If your AsciiDoc files use attributes that are defined outside of these files, you can supply the attribute definitions on the command line with the `-a _attribute_=_value_` option:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a _attribute_=_value_ _your_file_.adoc**
....

You can provide multiple `-a _attribute_=_value_` options at the same time. Providing relevant attribute definitions is especially important if your document contains conditional content.

.Providing a product version to resolve `ifeval` conditions
====
Your AsciiDoc files include a number of `ifeval` statements that provide different content for different versions of the product you are documenting:

[source]
----
\ifeval::["{ProductNumber}" == "1"]
...
\endif::[]
\ifeval::["{ProductNumber}" == "2"]
...
\endif::[]
----

To ensure that the converted DITA files include all content for version 2 of your product, run:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a ProductNumber=2 *.adoc**
....
====

[#types]
=== Enforcing a specialized topic type

Because the specialized `<concept>`, `<task>`, or `<reference>` topic types are restrictive in what block elements they can contain, in order to produce valid DITA output as much as possible, the `dita-topic` converter uses the generic `<topic>` element by default. To convert to one of the specialized topic types, set the value of the `dita-topic-type` attribute to `concept`, `reference`, or `task`:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a dita-topic-type=_type_ _your_file_.adoc**
....

.Converting AsciiDoc files with the `con_` prefix to DITA concepts
====
To convert all AsciiDoc files with the `con_` prefix to DITA concepts, run:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a dita-topic-type=concept con_*.adoc**
....

====

[#titles]
=== Disabling floating titles

Unlike AsciiDoc, DITA does not support floating titles and only allows titles to be assigned to a limited number of elements. To avoid losing content during the conversion, as a workaround, the `dita-topic` converter uses the following markup by default:

[source,xml]
----
<p outputclass="title"><b>Floating title</b></p>
----

To disable this behavior, set the value of the `dita-topic-titles` to `strict`:

[literal,subs="+quotes"]
....
$ **asciidoctor -r dita-topic -b dita-topic -a dita-topic-titles=strict _your_file_.adoc**
....

[#warnings]
== Warnings

Despite aspiring to avoid losing content during conversion and produce a valid DITA output, there are limitations to what is possible because of the differences between the two markup languages. When the `dita-topic` converter encounters a possible problem, it prints a warning to standard error output in the following format:

[literal,subs="+quotes"]
....
asciidoctor: WARNING: dita-topic: _The warning message_
....

This possible warning messages are as follows:

[horizontal]
Admonition titles not supported in DITA:: AsciiDoc allows you to add a custom title to any admonition by including `._Admonition title_` on the line above it. Unlike AsciiDoc, DITA does not allow titles for admonitions. `dita-topic` issues this warning whenever an admonition has a title defined in the converted AsciiDoc file.

Audio macro not supported:: AsciiDoc allows you to embed audio content in your documents by using the `audio::__audio_file__[]` macro. `dita-topic` does not implement this feature and issues this warning whenever the `audio` macro is present in the converted AsciiDoc file.

Block titles not supported in DITA:: AsciiDoc allows you to include `._Block title_` on the line above most of the block elements to assign a custom title to them. Unlike AsciiDoc, DITA only allows titles to be assigned to a limited number of elements. `dita-topic` issues this warning when the `-a dita-topic-titles=strict` option is specified and a block title is present in the converted AsciiDoc file.

Callout list support not implemented:: AsciiDoc allows you to use `<1>`, `<2>`, `<3>` and so on in verbatim blocks to add annotations to the specific lines. Unlike AsciiDoc, DITA does not provide a direct equivalent for this functionality. `dita-topic` issues this warning whenever these annotations are present in the converted AsciiDoc file, but I intend to emulate the AsciiDoc functionality by using a definition list in the upcoming release.

Floating titles not supported in DITA:: AsciiDoc allows you to use floating titles anywhere in the document. Unlike AsciiDoc, DITA does not support floating titles. `dita-topic` issues this warning when the `-a dita-topic-titles=strict` option is specified and a floating title is present in the converted AsciiDoc file.

Inline breaks not supported in DITA:: AsciiDoc provides multiple ways to insert line breaks in paragraphs, such as inserting `{nbsp}+` at the end of the line or specifying `[%hardbreaks]` on the line preceding the paragraph. Unlike AsciiDoc, DITA does not provide direct equivalent for this functionality. `dita-topic` issues this warning whenever an inline line break is present in the converted AsciiDoc file and places the `<!-- break -\->` comment in the output file to mark its place.

Inline index terms not implemented:: AsciiDoc allows you to define index terms within the text by using the `\indexterm2:[_primary_]` and `\indexterm:[_primary_, _secondary_, _tertiary_]` macros and their `\((_primary_))` and `(\((_primary_, _secondary_, _tertiary_)))` alternatives. `dita-topic` issues this warning whenever an index term is defined in the converted file, but as DITA does provide equivalent functionality, I intend to implement this feature in the upcoming release.

Nesting of sections not supported in DITA:: AsciiDoc allows you to nest sections up to 5 levels deep. Unlike AsciiDoc, DITA does not allow the `<section>` elements to be nested. `dita-topic` issues a warning whenever nested sections are present in the converted AsciiDoc file.

Page breaks not supported in DITA:: AsciiDoc allows you to use `<<<` on a separate line to enforce a page break in output formats that support it. Unlike AsciiDoc, DITA does not support page breaks. `dita-topic` issues this warning whenever a page break is present in the converted AsciiDoc file and places the `<p outputclass="page-break"></p>` in the output file to mark its place.

Possible invalid reference: _reference_:: AsciiDoc allows you to cross reference by using an ID no matter if this ID is defined within or outside of the converted document. Unlike AsciiDoc, DITA requires both the target ID and the ID of the target topic to be included in the cross reference if the reference leads outside of the current file. As `dita-topic` is meant to be run on individual AsciiDoc files, it does not have access to information from referenced files during conversion. `dita-topic` issues this warning whenever a cross reference is present in the converted AsciiDoc file.

STEM support not implemented:: AsciiDoc provides multiple ways to insert Science, Technology, Engineering and Math (STEM) expressions in the document, including the `\stem:[_formula_]` inline macro and the `[stem]` delimited block. `dita-topic` does not implement this feature and issues this warning whenever such an expression is present in the converted AsciiDoc file.

Table footers not supported in DITA:: AsciiDoc allows you to set the `footer` option to mark the last table row as a table footer. Unlike AsciiDoc, DITA does not support table footers. `dita-topic` issues this warning whenever a table footer is present in the converted AsciiDoc file.

Thematic breaks not supported in DITA:: Asciidoc allows you to use `'''`, `---`, or `\***` (the last two with possible optional spaces in between the characters) to insert a thematic break in between two blocks, most commonly represented by a horizontal line. Unlike AsciiDoc, DITA does not support thematic breaks. `dita-topic` issues this warning whenever a thematic break is present in the converted AsciiDoc file.

Video macro not supported:: AsciiDoc allows you to embed video content in your documents by using the `video::__video_file__[]` macro. `dita-topic` does not implement this feature and issues this warning whenever the `video` macro is present in the converted AsciiDoc file.

[#copyright]
== Copyright

Copyright (C) 2024 Jaromir Hradilek

This program is free software, released under the terms of the link:LICENSE[MIT license]. It is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
